"""add house id

Revision ID: 24c2f294d27d
Revises: f2a493ce5769
Create Date: 2025-12-10 13:57:17.814488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24c2f294d27d'
down_revision: Union[str, None] = 'f2a493ce5769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('base', sa.Column('id_house', sa.Integer(), nullable=False))
    op.add_column('button_events', sa.Column('id_house', sa.Integer(), nullable=False))
    op.add_column('interruptor', sa.Column('id_house', sa.Integer(), nullable=False))
    op.add_column('interruptor_lampada', sa.Column('id_house', sa.Integer(), nullable=False))
    op.add_column('lampada', sa.Column('id_house', sa.Integer(), nullable=False))
    op.add_column('logs', sa.Column('id_house', sa.Integer(), nullable=False))
    op.add_column('luzes', sa.Column('id_house', sa.Integer(), nullable=False))
    op.add_column('mappings', sa.Column('id_house', sa.Integer(), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('mappings', 'id_house')
        op.drop_column('luzes', 'id_house')
        op.drop_column('logs', 'id_house')
        op.drop_column('lampada', 'id_house')
        op.drop_column('interruptor_lampada', 'id_house')
        op.drop_column('interruptor', 'id_house')
        op.drop_column('button_events', 'id_house')
        op.drop_column('base', 'id_house')
    # ### end Alembic commands ###
