"""Initial migration

Revision ID: 0b799ea7f365
Revises: 
Create Date: 2025-12-03 16:58:59.943061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b799ea7f365'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_base_id'), 'base', ['id'], unique=False)
    op.create_index(op.f('ix_base_nome'), 'base', ['nome'], unique=True)
    op.alter_column('interruptor', 'base_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('interruptor', 'nome',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('interruptor', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Physical button state',
               existing_nullable=False)
    op.alter_column('interruptor', 'ativo',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Enabled/Disabled',
               existing_nullable=False)
    op.alter_column('interruptor', 'data_de_atualizacao',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
    op.create_index('idx_base_nome', 'interruptor', ['base_id', 'nome'], unique=False)
    op.create_index(op.f('ix_interruptor_base_id'), 'interruptor', ['base_id'], unique=False)
    op.create_index(op.f('ix_interruptor_id'), 'interruptor', ['id'], unique=False)
    op.create_index(op.f('ix_interruptor_nome'), 'interruptor', ['nome'], unique=False)
    op.drop_constraint(op.f('interruptor_ibfk_1'), 'interruptor', type_='foreignkey')
    op.create_foreign_key(None, 'interruptor', 'base', ['base_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interruptor_lampada', 'interruptor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('interruptor_lampada', 'lampada_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('interruptor_lampada', 'ordem',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Order for sequential activation',
               existing_nullable=True)
    op.create_index('idx_switch_lamp', 'interruptor_lampada', ['interruptor_id', 'lampada_id'], unique=True)
    op.create_index(op.f('ix_interruptor_lampada_id'), 'interruptor_lampada', ['id'], unique=False)
    op.drop_constraint(op.f('interruptor_lampada_ibfk_1'), 'interruptor_lampada', type_='foreignkey')
    op.drop_constraint(op.f('interruptor_lampada_ibfk_2'), 'interruptor_lampada', type_='foreignkey')
    op.create_foreign_key(None, 'interruptor_lampada', 'interruptor', ['interruptor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interruptor_lampada', 'lampada', ['lampada_id'], ['id'], ondelete='CASCADE')
    op.alter_column('lampada', 'base_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('lampada', 'nome',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('lampada', 'data_de_atualizacao',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index('idx_base_nome', 'lampada', ['base_id', 'nome'], unique=False)
    op.create_index(op.f('ix_lampada_base_id'), 'lampada', ['base_id'], unique=False)
    op.create_index(op.f('ix_lampada_id'), 'lampada', ['id'], unique=False)
    op.create_index(op.f('ix_lampada_nome'), 'lampada', ['nome'], unique=False)
    op.drop_constraint(op.f('lampada_ibfk_1'), 'lampada', type_='foreignkey')
    op.create_foreign_key(None, 'lampada', 'base', ['base_id'], ['id'], ondelete='CASCADE')
    op.alter_column('logs', 'comodo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('logs', 'data_hora',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index('idx_data_comodo', 'logs', ['data_hora', 'comodo'], unique=False)
    op.create_index(op.f('ix_logs_comodo'), 'logs', ['comodo'], unique=False)
    op.create_index(op.f('ix_logs_data_hora'), 'logs', ['data_hora'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_origem'), 'logs', ['origem'], unique=False)
    op.create_foreign_key(None, 'logs', 'luzes', ['comodo'], ['lampada'])
    op.alter_column('luzes', 'lampada',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('luzes', 'data_de_atualizacao',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_luzes_id'), 'luzes', ['id'], unique=False)
    op.create_index(op.f('ix_luzes_lampada'), 'luzes', ['lampada'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_luzes_lampada'), table_name='luzes')
    op.drop_index(op.f('ix_luzes_id'), table_name='luzes')
    op.alter_column('luzes', 'data_de_atualizacao',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('luzes', 'lampada',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_index(op.f('ix_logs_origem'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_data_hora'), table_name='logs')
    op.drop_index(op.f('ix_logs_comodo'), table_name='logs')
    op.drop_index('idx_data_comodo', table_name='logs')
    op.alter_column('logs', 'data_hora',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('logs', 'comodo',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'lampada', type_='foreignkey')
    op.create_foreign_key(op.f('lampada_ibfk_1'), 'lampada', 'base', ['base_id'], ['id'])
    op.drop_index(op.f('ix_lampada_nome'), table_name='lampada')
    op.drop_index(op.f('ix_lampada_id'), table_name='lampada')
    op.drop_index(op.f('ix_lampada_base_id'), table_name='lampada')
    op.drop_index('idx_base_nome', table_name='lampada')
    op.alter_column('lampada', 'data_de_atualizacao',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('lampada', 'nome',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('lampada', 'base_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'interruptor_lampada', type_='foreignkey')
    op.drop_constraint(None, 'interruptor_lampada', type_='foreignkey')
    op.create_foreign_key(op.f('interruptor_lampada_ibfk_2'), 'interruptor_lampada', 'interruptor', ['interruptor_id'], ['id'])
    op.create_foreign_key(op.f('interruptor_lampada_ibfk_1'), 'interruptor_lampada', 'lampada', ['lampada_id'], ['id'])
    op.drop_index(op.f('ix_interruptor_lampada_id'), table_name='interruptor_lampada')
    op.drop_index('idx_switch_lamp', table_name='interruptor_lampada')
    op.alter_column('interruptor_lampada', 'ordem',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Order for sequential activation',
               existing_nullable=True)
    op.alter_column('interruptor_lampada', 'lampada_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('interruptor_lampada', 'interruptor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'interruptor', type_='foreignkey')
    op.create_foreign_key(op.f('interruptor_ibfk_1'), 'interruptor', 'base', ['base_id'], ['id'])
    op.drop_index(op.f('ix_interruptor_nome'), table_name='interruptor')
    op.drop_index(op.f('ix_interruptor_id'), table_name='interruptor')
    op.drop_index(op.f('ix_interruptor_base_id'), table_name='interruptor')
    op.drop_index('idx_base_nome', table_name='interruptor')
    op.alter_column('interruptor', 'data_de_atualizacao',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('interruptor', 'ativo',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Enabled/Disabled',
               existing_nullable=False)
    op.alter_column('interruptor', 'estado',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Physical button state',
               existing_nullable=False)
    op.alter_column('interruptor', 'nome',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('interruptor', 'base_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index(op.f('ix_base_nome'), table_name='base')
    op.drop_index(op.f('ix_base_id'), table_name='base')
    # ### end Alembic commands ###
